# Generated by Django 5.1.7 on 2025-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'Número de identificación tributaria'), ('PP', 'Pasaporte'), ('PEP', 'Permiso especial de permanencia'), ('DIE', 'Documento de identificación extranjero')], max_length=255, unique=True),
        ),
    ]
