# Generated by Django 5.1.7 on 2025-04-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_tipodocumento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(default=1, max_length=255, unique=True),
        ),
    ]
