# Generated by Django 5.1.7 on 2025-04-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_tipodocumento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
