# Generated by Django 5.1.7 on 2025-04-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_empresa_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='estadoxactivo',
        ),
        migrations.AddField(
            model_name='activo',
            name='confidencialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.confidencialidad'),
        ),
        migrations.AddField(
            model_name='activo',
            name='criticidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.criticidad'),
        ),
        migrations.AddField(
            model_name='activo',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.disponibilidad'),
        ),
        migrations.AddField(
            model_name='activo',
            name='integridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.integridad'),
        ),
    ]
